[Rainmeter]
Update=1000
Author=Connect-R
BackgroundMode=2
SolidColor=0,0,0,1
DynamicWindowSize=1
AccurateText=1

MouseScrollUpAction=[!SetVariable Scale "(#Scale#+#ScrollMouseIncrement#)"][!WriteKeyValue Variables Scale "(#Scale#+#ScrollMouseIncrement#)"][!Refresh]
MouseScrollDownAction=[!SetVariable Scale "(#Scale#-#ScrollMouseIncrement# < 0.5 ? 0.5 : #Scale#-#ScrollMouseIncrement#)"][!WriteKeyValue Variables Scale "(#Scale#-#ScrollMouseIncrement# < 0.5 ? 0.5 : #Scale#-#ScrollMouseIncrement#)"][!Refresh]

; ----------------------------------------------------
; VARIABLES
; ----------------------------------------------------

[Variables]
Scale=1
CurrentIcon=moon.png
TextColor=255,255,255,230
LineColor=255,255,255,120
FontMain=Anurati
FontSub=Nexa Light
ScrollMouseIncrement=0.05

; ----------------------------------------------------
; TIME
; ----------------------------------------------------

[MeasureTime]
Measure=Time
Format=%I:%M

[MeasureAmPm]
Measure=Time
Format=%p

[MeasureDay]
Measure=Time
Format=%a

[MeasureDate]
Measure=Time
Format=%d %B %Y

; ----------------------------------------------------
; GREETING
; ----------------------------------------------------

[MeasureGreeting]
Measure=Time
Format=%H

IfTrueAction=[!SetOption MeterGreeting Text "GOOD#CRLF#EVENING"][!UpdateMeter MeterGreeting][!Redraw]

IfTrueAction2=[!SetOption MeterGreeting Text "GOOD#CRLF#AFTERNOON"][!UpdateMeter MeterGreeting][!Redraw]

IfTrueAction3=[!SetOption MeterGreeting Text "GOOD#CRLF#MORNING"][!UpdateMeter MeterGreeting][!Redraw]

DynamicVariables=1

; ----------------------------------------------------
; ICON SWITCH
; ----------------------------------------------------

[MeasureHour]
Measure=Time
Format=%H

IfCondition=(MeasureValue >= 20) || (MeasureValue < 5)
IfTrueAction=[!SetVariable CurrentIcon "moon.png"][!UpdateMeter *][!Redraw]

IfCondition2=(MeasureValue >= 5) && (MeasureValue < 11)
IfTrueAction2=[!SetVariable CurrentIcon "morning.png"][!UpdateMeter *][!Redraw]

IfCondition3=(MeasureValue >= 11) && (MeasureValue < 16)
IfTrueAction3=[!SetVariable CurrentIcon "noon.png"][!UpdateMeter *][!Redraw]

IfCondition4=(MeasureValue >= 16) && (MeasureValue < 20)
IfTrueAction4=[!SetVariable CurrentIcon "afternoon.png"][!UpdateMeter *][!Redraw]

DynamicVariables=1

; ----------------------------------------------------
; TOP ICON
; ----------------------------------------------------

[MeterIconTop]
Meter=Image
ImageName=#@#Images\graduation-cap.png
X=(133*#Scale#)
Y=(5*#Scale#)
W=(35*#Scale#)
H=(35*#Scale#)
PreserveAspectRatio=1
DynamicVariables=1

; ----------------------------------------------------
; TOP LINE
; ----------------------------------------------------

[MeterTopLine]
Meter=Shape
Shape=Line 0,0,0,120 | StrokeWidth 2 | Stroke Color #LineColor#
X=(150*#Scale#)
Y=(45*#Scale#)

; ----------------------------------------------------
; CENTER ICON
; ----------------------------------------------------

[MeterIconCenter]
Meter=Image
ImageName=#@#Images\#CurrentIcon#
X=(130*#Scale#)
Y=(195*#Scale#)
W=(35*#Scale#)
H=(35*#Scale#)
PreserveAspectRatio=1
DynamicVariables=1

; ----------------------------------------------------
; GREETING TEXT
; ----------------------------------------------------

[MeterGreeting]
Meter=String
Text=GOOD#CRLF#EVENING
StringAlign=CenterCenter
StringCase=Upper
FontFace=#FontSub#
FontColor=#TextColor#
FontSize=(11*#Scale#)
X=(150*#Scale#)
Y=(270*#Scale#)
AntiAlias=1

; ----------------------------------------------------
; DAY
; ----------------------------------------------------

[MeterDay]
Meter=String
MeasureName=MeasureDay
StringAlign=Center
StringCase=Upper
FontFace=#FontMain#
FontColor=#TextColor#
FontSize=(55*#Scale#)
X=(150*#Scale#)
Y=(297*#Scale#)
Text="%1"
InlineSetting=CharacterSpacing | 8 | 8
AntiAlias=1

; ----------------------------------------------------
; DATE
; ----------------------------------------------------

[MeterDate]
Meter=String
MeasureName=MeasureDate
StringAlign=Center
StringCase=Upper
FontFace=#FontSub#
FontColor=#TextColor#
FontSize=(14*#Scale#)
X=(150*#Scale#)
Y=(390*#Scale#)
AntiAlias=1

; ----------------------------------------------------
; TIME
; ----------------------------------------------------

[MeterTime]
Meter=String
MeasureName=MeasureTime
MeasureName2=MeasureAmPm
StringAlign=Center
StringCase=Upper
FontFace=#FontSub#
FontColor=#TextColor#
FontSize=(12*#Scale#)
X=(150*#Scale#)
Y=(420*#Scale#)
Text="%1 %2"
AntiAlias=1

; ----------------------------------------------------
; BOTTOM LINE
; ----------------------------------------------------

[MeterBottomLine]
Meter=Shape
Shape=Line 0,0,0,120 | StrokeWidth 2 | Stroke Color #LineColor#
X=(150*#Scale#)
Y=(470*#Scale#)

; ----------------------------------------------------
; BOTTOM ICON
; ----------------------------------------------------

[MeterIconBottom]
Meter=Image
ImageName=#@#Images\book.png
X=(135*#Scale#)
Y=(605*#Scale#)
W=(30*#Scale#)
H=(30*#Scale#)
PreserveAspectRatio=1
DynamicVariables=1